[Squash] GCC 5.0: Make kernel compatible These need to be static to avoid these errors:
drivers/built-in.o: In function `.LANCHOR1':
msm_iommu_sec.c:(.data+0x9298): undefined reference to `kgsl_iommu_sync_lock'
msm_iommu_sec.c:(.data+0x929c): undefined reference to `kgsl_iommu_sync_unlock'
Makefile:877: recipe for target '.tmp_vmlinux1' failed
make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Chet Kener <Cl3Kener@gmail.com>

Make kernel GCC 5.0 compatible

Change-Id: I627456842298eb9e66535c4a5635e3eb09e21527

gcc5: ARM: 8158/1: LLVMLinux: use static inline in ARM ftrace.h

With compilers which follow the C99 standard (like modern versions of gcc and
clang), "extern inline" does the wrong thing (emits code for an externally
linkable version of the inline function). In this case using static inline
and removing the NULL version of return_address in return_address.c does
the right thing.

Signed-off-by: Behan Webster <behanw@converseincode.com>
Reviewed-by: Mark Charlebois <charlebm@gmail.com>
Acked-by: Steven Rostedt <rostedt@goodmis.org>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Chet Kener <Cl3Kener@gmail.com>

gcc5: fix warnings spam with gcc5

This fixes 102 warnings

Signed-off-by: Paul Beeler <pbeeler80@gmail.com>

gcc5: sound/soc/codecs/wcd9xxx-mbhc.c fix warning: initialization discards 'const' qualifier from pointer target type

gcc5: drivers/staging/prima/CORE/MAC/src/pe/sch/schBeaconGen.c: fix warning: passing argument 2 of 'vos_mem_compare' discards 'const' qualifier from pointer target type

gcc5: drivers/staging/prima/CORE/HDD/src/wlan_hdd_wmm.c: fix warning: logical not is only applied to the left hand side of comparison

gcc5: drivers/video/msm/mdss/mdss_mdp_pp.c: fix warning: logical not is only applied to the left hand side of comparison

gcc5: drivers/video/msm/mdss/mdss_mdp_pp.c: fix warning: comparison of constant '15' with boolean expression is always false

gcc5: suppress more warnings

gcc5: makefile: remove wrapper

gcc5: try to fix errors

gcc5: try to fix again

Conflicts:
	Makefile